language: csharp
dotnet: 2.0.0
dist: trusty
script:
- dotnet restore src/Containo.API
- dotnet build src/Containo.API
branches:
  only:
  - master
notifications:
  email:
    on_success: never
    on_failure: always